### ISSUE TITLE
Error: Cannot find module './node_modules/canvas'

### ISSUE THREAD

**Issue by cyf0611** [zhuweiyou/weixin-game-helper#1]
大佬，这个canvas模块不太好安装啊，看了这个还是没安好，https://github.com/Automattic/node-canvas/wiki/Installation---Windows             
你是怎么安的。。。

**Comment by zhuweiyou** [comment]
我机器是 mac ，你放个 win 报错截图我看看？另外你的 node 版本多少

**Comment by cyf0611** [comment]
![image](https://user-images.githubusercontent.com/25743955/34477614-51086492-efd6-11e7-8c3c-57131f3f7572.png)

**Comment by zhuweiyou** [comment]
我跑个 win 虚拟机测试一下再反馈你

**Comment by cyf0611** [comment]
好的  谢谢

**Comment by zhuweiyou** [comment]
这玩意确实蛮难装的，我找到了 [canvas-prebuilt](https://www.npmjs.com/package/canvas-prebuilt) 来代替

已经重新调整了代码，clone 最新的代码试试看

**Comment by cyf0611** [comment]
大佬，怎么不能自动点击

**Comment by zhuweiyou** [comment]
像素比对之后，会有几百个点不同，如果用自动点击的话，游戏就直接输了（找茬有点击次数限制）

所以需要有一个算法，来关联一组像素点的区域（圈成矩形），然后一个矩形点一次才行

所以目前只做到手动

**Comment by zhuweiyou** [comment]
辅助已升级，完全在手机上操作即可，非常高效 https://github.com/zhuweiyou/weixin-game-helper/pull/22
