### ISSUE TITLE
答题页面不显示？

### ISSUE THREAD

**Issue by flyshu** [zhuweiyou/weixin-game-helper#12]
执行npm run robot之后，进入答题 只显示背景色，30s后提示timeout？

**Comment by zhuweiyou** [comment]
这应该是没有配置好代理，或者证书没装好。你检查下

**Comment by flyshu** [comment]
[AnyProxy Log][2018-01-24 21:13:18]: received https CONNECT request wx.qlogo.cn
[AnyProxy Log][2018-01-24 21:13:18]: will forward to local https server
[AnyProxy Log][2018-01-24 21:13:19]: [internal https]proxy server for wx.qlogo.cn established
[AnyProxy Log][2018-01-24 21:13:19]: received request to: GET wx.qlogo.cn/mmopen/vi_32/DYAIOgq83erONCy5fvOX0CJShYzquY8ibQlz5qke9pjicibO3Qq0SXvIm28ic6EFaEf8DFUkjnFxEzvkbAiaZzs1ibew/0
[AnyProxy Log][2018-01-24 21:13:23]: received https CONNECT request question.hortor.net
[AnyProxy Log][2018-01-24 21:13:23]: will forward to local https server
[AnyProxy Log][2018-01-24 21:13:23]: received request to: POST question.hortor.net/question/bat/findQuiz
[题目信息] {"quiz":"在对手没有犯规的情况下，斯诺克单杆最高得分是？","options":["255分","44分","147分","100分"],"num":1,"school":"流行","type":"体育","typeID":18,"contributor":"","partner":0,"endTime":1516799615,"curTime":1516799601,"myBuff":{}}
(node:8292) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[AnyProxy Log][2018-01-24 21:13:31]: received https CONNECT request question.hortor.net
[AnyProxy Log][2018-01-24 21:13:31]: will forward to local https server
[AnyProxy Log][2018-01-24 21:13:31]: received request to: POST question.hortor.net/question/bat/findQuiz
[题目信息] {"quiz":"在对手没有犯规的情况下，斯诺克单杆最高得分是？","options":["255分","44分","147分","100分"],"num":1,"school":"流行","type":"体育","typeID":18,"contributor":"","partner":0,"endTime":1516799615,"curTime":1516799610,"myBuff":{}}

**Comment by flyshu** [comment]
pc上能刷新出题目 代理应该没问题 但不知道微信端为什么会timeput

**Comment by zhuweiyou** [comment]
嗯，看起来代理是没问题的

- 数据库是否连上？
- `node -v` 版本多少？

https://github.com/zhuweiyou/weixin-game-helper/blob/9d2a7a2c103e4aaaa2a0556198f474a363168b38/%E5%A4%B4%E8%84%91%E7%8E%8B%E8%80%85/src/robot.js#L22

在这行代码之后加个 log
```js
console.log(this._quiz)
```
看下打印结果

**Comment by flyshu** [comment]
感谢。解决了 果然是数据库没有连上的问题，但是没有报错，看了似乎是只有链接成功会有输出，失败反而没有任何提示

**Comment by zhuweiyou** [comment]
我后续加一下 失败的提示。
