### ISSUE TITLE
如何抓取登录请求拿到 session_id、openid

### ISSUE THREAD

**Issue by zhuweiyou** [zhuweiyou/weixin-game-helper#13]
假设你已经阅读  [如何抓取微信小程序 HTTPS 请求](https://github.com/zhuweiyou/weixin-game-helper/issues/6)

先打开抓包工具，**完全退出游戏进程**，重新进入小游戏

一般来说第一个 API 请求，或者 URL 上带有 login 之类字符串，就是登录请求了

如果没有就挨个看看 Request 和 Response 内容，就能找到。如图：

![image](https://user-images.githubusercontent.com/8413791/35369077-4e8c49ac-01c1-11e8-90e9-d65374aabdea.png)

每个小游戏网络请求不太一样，自己多看看就能找到了

**Comment by huaji1992** [comment]
找到后怎么修改然后发送请求呢
