### ISSUE TITLE
如何抓取微信小程序 HTTPS 请求

### ISSUE THREAD

**Issue by zhuweiyou** [zhuweiyou/weixin-game-helper#6]
## mac

推荐使用 Charles

- 菜单 -> Proxy -> SSL Proxying Settings... -> 勾选Enable SSL Proxying -> 点击Add  -> 填入 * 抓所有域名

![image](https://user-images.githubusercontent.com/8413791/34810238-03f72f70-f6d5-11e7-99b2-32871f6a4b46.png)

-  菜单 -> Help -> SSL Proxying 

![image](https://user-images.githubusercontent.com/8413791/34810057-1e342902-f6d4-11e7-9619-fa51675bba08.png)

![image](https://user-images.githubusercontent.com/8413791/34810106-578105a4-f6d4-11e7-80a8-a95be83bb0ea.png)

确保手机和电脑处于同一个局域网下，并在手机上设置代理 IP 和 端口（你电脑的局域网 IP 和抓包工具设置的端口，通常为 `8080` 或者 `8888` 也可以自己设置）

手机访问 `chls.pro/ssl` 地址，下载和安装抓包工具的 CA 证书。

部分 iOS 系统需要在：设置 -> 通用 -> 关于本机 -> 证书信任设置 -> 启用完全信任Charles证书

## win

推荐使用 Fiddler

- 菜单 -> Tools -> Fiddler Options... -> Decrypt HTTPS traffic

- 点击右上角的Actions => 点击Export Root Certificate to Desktop

- 导入证书并安装 

手机连接到电脑上，从电脑上打开手机的内存卡，直接把证书导入SD卡中。点击设置 -> 安全 -> 从 SD 卡安装 -> 从内部存储空间中找到证书，点击安装即可（不能直接点击安装，会出现无法安装证书，因为无法读取证书文件。）

> 暂时没有 win 的图，有的欢迎截图补充，大概的操作方式都一样

**Comment by mkuai** [comment]
请教一下：我用Fiddler可以抓取【我最在行】登录时信息（排名，擂台名称，等），可是进入答题的以后就不能抓到任何和该程序有关的https的包了，应该是服务器端做了某种验证吧？我看到你们的程序中加了相应的部分，请问可以设置Fiddler来抓取这些包吗？谢谢！

**Comment by zhuweiyou** [comment]
答题使用的是 websocket 通讯，所以 Fiddler 抓不到了。

用 wireshark 之类的抓包工具应该可以，不过可能不是明文。

**Comment by xuzzzeng** [comment]
iPhone怎么导入证书？

**Comment by zhuweiyou** [comment]
@xuzzzeng  Safari 浏览器打开，`chls.pro/ssl`

**Comment by handsomeJJ** [comment]
![wx20180307-143315](https://user-images.githubusercontent.com/18132216/37077114-75e84870-2214-11e8-963c-803637cd79c0.png)
已经设置了HTTPS抓取mp.weixin.qq.com，为何抓不到数据呢？是版本问题吗？我的青花瓷版本是V4.1.3

**Comment by zhuweiyou** [comment]
@handsomeJJ 你可以尝试抓下不是微信的页面 HTTPS，如果正常抓的话。

说明微信 APP 拒绝了抓包工具，就抓不到了。

**Comment by handsomeJJ** [comment]
你那边什么版本？是否还能抓得到，我这HTTPS有的行有的不行

**Comment by rancho521** [comment]
![1](https://user-images.githubusercontent.com/30742467/37861009-ede920d8-2f6b-11e8-92ac-53264b25eade.png)
@zhuweiyou 请教一下，我抓登录请求的时候，抓到的协议里带有cipher，请问这样怎么办？

**Comment by zhuweiyou** [comment]
fiddler 不是很了解，你不用看这个吧，看  JSON 就好。
只要配好了证书，就可以解析 HTTPS 明文的。
